name: Generate UML from Solidity Contracts

on: [push, pull_request]

jobs:
  generate-uml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Run sol2uml in Docker
      run: |
        docker run --rm -v $(pwd)/contracts:/contracts sol2uml/sol2uml /contracts/BaseCertificate.sol /contracts/CdobCertificate.sol /contracts/CertificateManager.sol \
        /contracts/CpotbCertificate.sol /contracts/ObatTradisional.sol /contracts/OrderManagement.sol \
        /contracts/RoleManager.sol /contracts/NieManager.sol /contracts/EnumsLibrary.sol /contracts/ObatShared.sol \
        -o /contracts/output-folder/
          
    - name: Upload UML Diagrams
      uses: actions/upload-artifact@v4
      with:
        name: uml-diagrams
        path: output-folder/*.png
