name: Slither Analysis

on: [push, pull_request]

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Solidity Compiler
        run: |
          pip install solc-select
          solc-select install 0.8.27
          solc-select use 0.8.27

      - name: Install Slither
        run: pip install slither-analyzer

      - name: List Contract Files
        run: ls -R contracts/ || echo "No contracts found!"

      - name: Run Slither and Show Logs
        run: |
          mkdir -p slither-reports
          for file in contracts/*.sol; do
            echo "Running Slither on $file"
            slither "$file" || echo "Slither failed for $file"
          done

      - name: Debug JSON Output
        run: |
          echo "Checking Slither reports..."
          ls -lah slither-reports/
          cat slither-reports/*.json || echo "No Slither output found"

      - name: Ensure JSON File Exists
        run: |
          for file in slither-reports/*.json; do
            if [ ! -s "$file" ]; then
              echo '{"status": "No issues found"}' > "$file"
              echo "Replaced empty JSON for $file"
            fi
          done


      - name: Upload Slither Report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-reports/slither-output.json
