name: Slither Analysis

on: [push, pull_request]

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Solidity Compiler
        run: |
          pip install solc-select
          solc-select install 0.8.27
          solc-select use 0.8.27

      - name: Install Slither
        run: pip install slither-analyzer

      - name: List Contract Files
        run: ls -R contracts/ || echo "No contracts found!"

      - name: Run Slither Analysis
        run: |
          mkdir -p slither-reports
          slither contracts/ --json slither-reports/slither-output.json || echo "Slither encountered issues but continuing..."
        continue-on-error: true

      - name: Debug Slither Output
        run: cat slither-reports/slither-output.json || echo "Slither output is empty"

      - name: Ensure JSON File Exists
        run: |
          if [ ! -s slither-reports/slither-output.json ]; then
            echo '{"status": "No issues found"}' > slither-reports/slither-output.json
            echo "Slither report was empty, added default status."
          fi

      - name: Upload Slither Report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-reports/slither-output.json
